#server:
#  port: 8080
#
#spring:
#  datasource:
#  #For External datasource
##    url: jdbc:mysql://localhost:3307/moraspringsecurity01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
##    username: root
##    password: root
#    #For External h2 datasource
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
